services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin-mediaserver
    ports:
      - "8096:8096"
    volumes:
      - ./config:/config
      - ${MEDIA_PATH}/Filmer:/Filmer
      - ${MEDIA_PATH}/TV Serier:/Serier
      - ${MEDIA_PATH}/Musikk:/Musikk
    restart: unless-stopped